### ISSUE TITLE
Bot shouldn't give poaps to other bots

### ISSUE THREAD

**Issue by fvictorio** [gitpoap/gitpoap-bot#11]
See for example [here](https://github.com/NomicFoundation/hardhat/pull/2968#issuecomment-1216393649).

**Comment by peebeejay** [comment]
thx for bringing this to our attention @fvictorio. 

interestingly enough, we released some code yesterday to prevent this from happening in our claim creation routes, but may have missed this one. 

@burz - could you take a look? perhaps the bot/claims endpoint needs to be updated to ignore bots too?

**Comment by burz** [comment]
Thanks for pointing this out, @fvictorio! We appreciate it, and this should not happen going into the future.
